const img = (casa: string, file: string) =>
  `/casas/fotos-casas/${encodeURIComponent(casa)}/${encodeURIComponent(file)}`

export const projects = [
  {
    id: 1,
    image: img("Residência RL", "DJI_0875 (1).webp"),
    alt: "Residência RL - Campinas",
    title: "Residência RL",
    category: "Residencial",
    location: "Campinas - SP",
    area: "663,34m²",
    terreno: "1.000m²",
    architect: "Padovani Arquitetos",
    interior: "Lenina",
    photographer: "Miro Martins",
    description: "Residência Minimalista de Design Assinado",
    detailedDescription:
      "Em um lote de 1.000m², esta residência de 700m² de área construída pela PAGV personifica a arquitetura minimalista com elegância e inovação. A estrutura mista, que combina concreto, madeira e elementos metálicos, foi estrategicamente concebida para conferir leveza visual e máxima eficiência construtiva ao projeto. O destaque da obra reside nos painéis ripados metálicos, um elemento desenvolvido em colaboração com a equipe de arquitetura, que se integra perfeitamente à volumetria da fachada, criando um jogo de texturas e luz. Internamente, o uso de forros de madeira e pedras naturais selecionadas acentua o alto nível de sofisticação e o bom gosto, transformando cada ambiente em uma expressão de Arte e Design contemporâneo.",
    services: ["Construção Completa", "Gerenciamento de Obras", "Acabamentos Premium"],
    gallery: [
      img("Residência RL", "DJI_0875 (1).webp"),
      img("Residência RL", "DJI_0876.webp"),
      img("Residência RL", "DSC02330.webp"),
      img("Residência RL", "DSC02332 (1).webp"),
      img("Residência RL", "_DSC8961.webp"),
      img("Residência RL", "_DSC8965.webp"),
      img("Residência RL", "_DSC8976.webp"),
      img("Residência RL", "_DSC8986.webp"),
      img("Residência RL", "_DSC9026.webp"),
      img("Residência RL", "_DSC9047.webp"),
      img("Residência RL", "_DSC9048-Editar.webp"),
      img("Residência RL", "_DSC9053.webp"),
      img("Residência RL", "_DSC9062.webp"),
      img("Residência RL", "_DSC9090-Editar.webp"),
      img("Residência RL", "_DSC9105-Editar.webp"),
      img("Residência RL", "_DSC9119-Editar-2.webp"),
      img("Residência RL", "_DSC9145-Editar.webp"),
      img("Residência RL", "_DSC9154.webp"),
      img("Residência RL", "_DSC9155.webp"),
      img("Residência RL", "_DSC9164-Editar.webp"),
    ],
  },
  {
    id: 2,
    image: img("Residência LB", "Pagv - Casa Valinhos (26).webp"),
    alt: "Residência LB - Valinhos",
    title: "Residência LB",
    category: "Residencial",
    location: "Valinhos - SP",
    area: "663,34m²",
    terreno: "2.400m²",
    architect: "Arquitetura 4",
    interior: "Priscila Alves Arquitetura",
    photographer: "Pólen Producer",
    description: "Assessoria Completa e Residência Integrada",
    detailedDescription:
      "Este projeto singular é um testemunho da Parceria e Gestão abrangente oferecida pela PAGV. Por um ano e meio, assessoramos o cliente desde a criteriosa escolha do lote de 2.400m², estendendo-se à indicação dos arquitetos e profissionais que deram vida a esta residência. Com mais de 600m² de área construída em um pavimento térreo, a casa se destaca por seu paisagismo impressionante e pela concepção de todos os espaços para um ótimo convívio. O resultado é um lar que oferece funcionalidade, bem-estar e um Valor excepcional, cuidadosamente planejado para a vida em família.",
    services: ["Assessoria Completa", "Gerenciamento de Projeto", "Coordenação Arquitetônica"],
    gallery: [
      img("Residência LB", "Pagv - Casa Valinhos (26).webp"),
      img("Residência LB", "Pagv - Casa Valinhos (32).webp"),
      img("Residência LB", "Pagv - Casa Valinhos (35).webp"),
      img("Residência LB", "Pagv - Casa Valinhos (37).webp"),
      img("Residência LB", "Pagv - Casa Valinhos (46).webp"),
      img("Residência LB", "Pagv - Casa Valinhos (55).webp"),
      img("Residência LB", "Pagv - Casa Valinhos (66).webp"),
    ],
  },
  {
    id: 3,
    image: img("Residência MG", "seleção PAGV-1 (1).webp"),
    alt: "Residência MG - Vinhedo",
    title: "Residência MG",
    category: "Residencial",
    location: "Vinhedo - SP",
    area: "332,20m²",
    terreno: "Não informado",
    architect: "Priscila Alves",
    interior: "Priscila Alves",
    photographer: "Pólen Producer",
    description: "Elegância e Acolhimento",
    detailedDescription:
      "Nesta residência, a PAGV concebeu uma obra-prima onde a elegância contemporânea se funde perfeitamente com o conforto acolhedor. A Arte de projetar é evidente no uso estratégico de materiais naturais – como a pedra bruta e a madeira – que conferem textura, calor e sofisticação inigualáveis ao conjunto. Destacam-se a convidativa cozinha gourmet, com seu charmoso fogão à lenha e integração fluida com a área externa, aproveitando a iluminação natural e a ventilação cruzada. A imponente lareira em pedra, protagonista do ambiente, é emoldurada por amplos panos de vidro que conectam o interior ao jardim exuberante, criando um cenário de puro aconchego. Este projeto expressa o compromisso da PAGV em entregar Valor através de materiais nobres, funcionalidade e bem-estar, unindo técnica apurada e estética refinada em cada detalhe.",
    services: ["Construção Completa", "Acabamentos Nobres", "Integração Paisagística"],
    gallery: [
      img("Residência MG", "seleção PAGV-1 (1).webp"),
      img("Residência MG", "seleção PAGV-17.webp"),
      img("Residência MG", "seleção PAGV-2 (1).webp"),
      img("Residência MG", "seleção PAGV-20.webp"),
      img("Residência MG", "seleção PAGV-26.webp"),
      img("Residência MG", "seleção PAGV-29 (1).webp"),
      img("Residência MG", "seleção PAGV-33.webp"),
      img("Residência MG", "seleção PAGV-38.webp"),
      img("Residência MG", "seleção PAGV-4.webp"),
    ],
  },
  {
    id: 4,
    image: img("Residência LM", "DJI_0037.webp"),
    alt: "Residência LM - Campinas",
    title: "Residência LM",
    category: "Residencial",
    location: "Campinas - SP",
    area: "~1.000m²",
    terreno: "2.600m²",
    architect: "Não informado",
    interior: "Elaine Carvalho",
    photographer: "Miro Martins",
    description: "Elegante e Atemporal",
    detailedDescription:
      "Esta residência foi executada em um terreno de 2.600m², com 1.000m² de área construída. O projeto apresenta uma implantação precisa e harmoniosa, integrando-se naturalmente à paisagem e ao exuberante jardim existente. A utilização de materiais de altíssimo padrão e bom gosto resultou em uma fachada imponente, marcada pela elegância e proporção. O principal desafio deste empreendimento foi atender ao prazo reduzido solicitado pelo cliente, o que exigiu uma execução ágil e rigorosamente planejada, sem qualquer concessão quanto à qualidade e ao nível de acabamento.",
    services: ["Gerenciamento de Obras", "Construção Completa", "Cronograma Crítico"],
    gallery: [
      img("Residência LM", "DJI_0037.webp"),
      img("Residência LM", "DJI_0057.webp"),
      img("Residência LM", "_DSC5676-Editar.webp"),
      img("Residência LM", "_DSC5680.webp"),
      img("Residência LM", "_DSC5691.webp"),
      img("Residência LM", "_DSC5716.webp"),
      img("Residência LM", "_DSC5748-Editar.webp"),
      img("Residência LM", "_DSC5756-Editar.webp"),
      img("Residência LM", "_DSC5776.webp"),
      img("Residência LM", "_DSC5931-Editar.webp"),
      img("Residência LM", "_DSC5935.webp"),
      img("Residência LM", "_DSC5971-Editar.webp"),
      img("Residência LM", "_DSC5973-Editar.webp"),
      img("Residência LM", "_DSC5982-Editar.webp"),
      img("Residência LM", "_DSC5985-Editar.webp"),
      img("Residência LM", "_DSC5986-Editar.webp"),
      img("Residência LM", "_DSC5995-Editar.webp"),
      img("Residência LM", "_DSC5997-Editar.webp"),
    ],
  },
  {
    id: 5,
    image: img("Residência BM", "FOTOS CASA PAULÍNIA - @polen.producer-1.webp"),
    alt: "Residência BM - Paulínia",
    title: "Residência BM",
    category: "Residencial",
    location: "Paulínia - SP",
    area: "255,48m²",
    terreno: "Não informado",
    architect: "Não informado",
    interior: "Carol Conter Arquitetura",
    photographer: "Pólen Producer",
    description: "Modernidade e Funcionalidade",
    detailedDescription:
      "Desenvolvida para um jovem casal, esta residência da PAGV materializa um conceito que eleva os espaços de convivência a um novo patamar. Ambientes como a adega, o sofisticado espaço gourmet e a piscina foram habilmente integrados, promovendo uma fluidez impecável para o uso diário e momentos de lazer. O resultado é um lar que harmoniza acolhimento, funcionalidade e sofisticação. Cada detalhe reflete a Arte da PAGV em criar projetos que agregam Valor genuíno, entregando um refúgio ideal para a celebração da vida familiar e social.",
    services: ["Construção Residencial", "Espaços Gourmet", "Integração de Ambientes"],
    gallery: [
      img("Residência BM", "FOTOS CASA PAULÍNIA - @polen.producer-1.webp"),
      img("Residência BM", "FOTOS CASA PAULÍNIA - @polen.producer-12.webp"),
      img("Residência BM", "FOTOS CASA PAULÍNIA - @polen.producer-38.webp"),
      img("Residência BM", "FOTOS CASA PAULÍNIA - @polen.producer-48.webp"),
      img("Residência BM", "FOTOS CASA PAULÍNIA - @polen.producer-67.webp"),
      img("Residência BM", "FOTOS CASA PAULÍNIA - @polen.producer-95.webp"),
    ],
  },
]
